version: "3.8"

services:
  database:
    image: "postgres:17-alpine"
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: svgv
      POSTGRES_PASSWORD: svgv
      POSTGRES_DB: postgres
